/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package space.nicholasblackburn.minigames.simonsays;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
